# Task 1

---

## Web scraping and analysis

This Jupyter notebook includes some code to get you started with web scraping. We will use a package called `BeautifulSoup` to collect the data from the web. Once you've collected your data and saved it into a local `.csv` file you should start with your analysis.

### Scraping data from Skytrax

If you visit [https://www.airlinequality.com] you can see that there is a lot of data there. For this task, we are only interested in reviews related to British Airways and the Airline itself.

If you navigate to this link: [https://www.airlinequality.com/airline-reviews/british-airways] you will see this data. Now, we can use `Python` and `BeautifulSoup` to collect all the links to the reviews and then to collect the text data on each of the individual review links.

In [47]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [48]:
base_url = "https://www.airlinequality.com/airline-reviews/british-airways"
pages = 30
page_size = 100

reviews = []
table_data = []

# for i in range(1, pages + 1):
for i in range(1, pages + 1):

    print(f"Scraping page {i}")

    # Create URL to collect links from paginated data
    url = f"{base_url}/page/{i}/?sortby=post_date%3ADesc&pagesize={page_size}"

    # Collect HTML data from this page
    response = requests.get(url)

    # Parse content
    content = response.content
    parsed_content = BeautifulSoup(content, 'html.parser')
    for para in parsed_content.find_all("div", {"class": "text_content"}):
        reviews.append(para.get_text())
    flag = True
    #ChatGPT helped me figure out how to make sense of table structures
    for table in parsed_content.find_all("div", {"class": "review-stats"}):
        individual_stars = []
        table_rows = table.find_all("tr")
#         print(".") #just seeing if it detects the classes at all
        for row in table_rows:
            cells = row.find_all("td")
            feature = cells[0].text
            if cells[1].text == '12345':
                response = str(cells[1]).count('star fill') #YAY
#                 if flag:
#                     print(response)
#                     flag = False
            else: 
                response = cells[1].text
            individual_stars.append((feature, response))
        table_data.append(individual_stars)

    print(f"   ---> {len(reviews)} total reviews")

Scraping page 1
   ---> 100 total reviews
Scraping page 2
   ---> 200 total reviews
Scraping page 3
   ---> 300 total reviews
Scraping page 4
   ---> 400 total reviews
Scraping page 5
   ---> 500 total reviews
Scraping page 6
   ---> 600 total reviews
Scraping page 7
   ---> 700 total reviews
Scraping page 8
   ---> 800 total reviews
Scraping page 9
   ---> 900 total reviews
Scraping page 10
   ---> 1000 total reviews
Scraping page 11
   ---> 1100 total reviews
Scraping page 12
   ---> 1200 total reviews
Scraping page 13
   ---> 1300 total reviews
Scraping page 14
   ---> 1400 total reviews
Scraping page 15
   ---> 1500 total reviews
Scraping page 16
   ---> 1600 total reviews
Scraping page 17
   ---> 1700 total reviews
Scraping page 18
   ---> 1800 total reviews
Scraping page 19
   ---> 1900 total reviews
Scraping page 20
   ---> 2000 total reviews
Scraping page 21
   ---> 2100 total reviews
Scraping page 22
   ---> 2200 total reviews
Scraping page 23
   ---> 2300 total reviews
Scraping page 24
   ---> 2400 total reviews
Scraping page 25
   ---> 2500 total reviews
Scraping page 26
   ---> 2600 total reviews
Scraping page 27
   ---> 2700 total reviews
Scraping page 28
   ---> 2800 total reviews
Scraping page 29
   ---> 2900 total reviews
Scraping page 30
   ---> 3000 total reviews

In [49]:
df = pd.DataFrame()
df["reviews"] = reviews
# df["stars"] = table_data
df.head()

                                             reviews
0  Not Verified |  Extremely rude ground service....
1  ✅ Trip Verified |  My son and I flew to Geneva...
2  ✅ Trip Verified |  For the price paid (bought ...
3  ✅ Trip Verified |  Flight left on time and arr...
4  ✅ Trip Verified |  Very Poor Business class pr...

In [50]:
# Should do some more cleaning
# figure out how may categories to put in the df
categories = {}

#this is for each review
for entry_index in table_data: 
    #not everyone input the same information about features
    for num_features in range(len(entry_index)):
        if entry_index[num_features][0] not in categories:
            categories[entry_index[num_features][0]] = True
        else: 
            next
# there are 13 categories
# print(len(categories))

In [51]:
# need to all all the categories into the dataframe
df[list(categories.keys())] = None
df.head()

,reviews,Type Of Traveller,Seat Type,Route,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Value For Money,Recommended,Inflight Entertainment,Wifi & Connectivity,Aircraft
0,Not Verified | Extremely rude ground service....,None,None,None,None,None,None,None,None,None,None,None,None,None
1,✅ Trip Verified | My son and I flew to Geneva...,None,None,None,None,None,None,None,None,None,None,None,None,None
2,✅ Trip Verified | For the price paid (bought ...,None,None,None,None,None,None,None,None,None,None,None,None,None
3,✅ Trip Verified | Flight left on time and arr...,None,None,None,None,None,None,None,None,None,None,None,None,None
4,✅ Trip Verified | Very Poor Business class pr...,None,None,None,None,None,None,None,None,None,None,None,None,None

In [52]:
flag = True

#for each person who input star ratings
for entry in range(len(table_data)):
    
    # a row per person
    star_row = table_data[entry]
    
    # for each of the features they mention
    for num_features in range(len(star_row)):
        feature_name = star_row[num_features][0]
        
        if feature_name in categories: 
            if flag:
                print(feature_name)
                flag = False
            df.loc[entry,feature_name] = str(star_row[num_features][1])              
        else: 
            next
df.head()

Type Of Traveller

,reviews,Type Of Traveller,Seat Type,Route,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Value For Money,Recommended,Inflight Entertainment,Wifi & Connectivity,Aircraft
0,Not Verified | Extremely rude ground service....,Family Leisure,Economy Class,Rome to London,January 2024,4,5,4,1,2,no,None,None,None
1,✅ Trip Verified | My son and I flew to Geneva...,Family Leisure,Business Class,Gatwick to Geneva,December 2023,2,1,1,1,1,no,1,1,None
2,✅ Trip Verified | For the price paid (bought ...,Solo Leisure,Business Class,Istanbul to London Heathrow,December 2023,1,4,5,2,4,yes,1,None,A320
3,✅ Trip Verified | Flight left on time and arr...,Solo Leisure,Economy Class,London Heathrow to Istanbul,December 2023,3,2,1,5,2,no,1,None,A320
4,✅ Trip Verified | Very Poor Business class pr...,Business,Business Class,Gatwick to St Lucia,December 2023,1,5,2,1,2,no,2,2,Boeing 777

In [53]:
df.to_csv("./BA_reviews.csv")

Congratulations! Now you have your dataset for this task! The loops above collected 1000 reviews by iterating through the paginated pages on the website. However, if you want to collect more data, try increasing the number of pages!

 The next thing that you should do is clean this data to remove any unnecessary text from each of the rows. For example, "✅ Trip Verified" can be removed from each row if it exists, as it's not relevant to what we want to investigate.